export const StudentsTestimonies = [
  {
        id: 16,
        created_at: "2025-05-28 21:47:48.355868+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "E-learning has helped me a lot by giving me flexible access to learning materials anytime and anywhere. Since I signed up, I\u2019ve become more independent in my learning, improved my digital skills, and gained a better understanding of the subjects I study. ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "Non suggestion ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "My overall impression of E-learning is very positive. It provides flexibility, easy access to information, and allows me to learn at my own pace.",
        user_name: "Anne ",
        user_firstname: "Floriane ",
        pseudo: "Anne Floriane "
    },
  {
        id: 12,
        created_at: "2025-05-28 19:53:55.371856+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "First of all E-learning has learned us how to speak freely in public without being afraid, this lead to improve our skills of speaking in English language.\nMoreover E-learning help us by highlighting (explaining)more on every course, it answers all exam papers \nand even questions brought by us. \nAll in all,since we signed up for E-learning , we capitalize all our units with good marks.\nThanks !",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "E-learning is perfect.",
        user_name: "TIYOU",
        user_firstname: "Nixty ",
        pseudo: "Nixty TIYOU "
    },
    {
        id: 15,
        created_at: "2025-05-28 21:18:24.75011+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "Thanks for everything you've created an amazing thing ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English Only",
        suggestions: "More content ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Nice ",
        user_name: "Ghost ",
        user_firstname: "Lord",
        pseudo: "MARTOUKA Ir\u00e9n\u00e9e "
    },
    {
        id: 84,
        created_at: "2025-06-25 13:37:15.248133+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "Since joining the E-learning platform, It has helped me grow both personally and academically at my own pace.",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Awesome",
        language_to_speak: "English Only",
        suggestions: "I propose enhancing the platform\u2019s interactivity by integrating more practical activities and fostering peer-to-peer exchanges. This approach would not only deepen engagement but also enrich the overall learning experience.\nAdditionally, placing greater emphasis on core values such as discipline, respect, and humility ,particularly in student interactions would help cultivate a culture of mutual consideration. Such a culture promotes a more harmonious environment and reinforces group cohesion.",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "My overall experience with E-learning has been highly positive. It has enabled me to learn with autonomy, discipline, and consistent progress at my own pace.",
        user_name: "ANANI",
        user_firstname: "Kokou Othniel",
        pseudo: "E-member"
    },
    {
        id: 31,
        created_at: "2025-05-30 12:28:10.238162+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "A deep understanding of my courses, novels and plays.\nImprove my speaking skills.",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Awesome",
        language_to_speak: "English & French",
        suggestions: "No suggestion",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Very amazing.",
        user_name: "KPASSE Palakiy\u00e9m Hyacenthe",
        user_firstname: "Hyacenthe",
        pseudo: "Hyacenthe"
    },
  {
        id: 9,
        created_at: "2025-05-28 16:32:37.83379+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "Gr\u00e2ce \u00e0 cela j'ai p\u00fb valider les mati\u00e8res et \u00e7a m'a aid\u00e9 \u00e0 mieux comprendre l'anglais ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "Aucune suggestion ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "G\u00e9nial ",
        user_name: "OUBOTE ",
        user_firstname: "Elisabeth ",
        pseudo: "Elise "
    },
    {
        id: 11,
        created_at: "2025-05-28 19:52:30.222113+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "J'ai eu de très bonnes notes l'année dernière ",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "I like it",
        user_name: "Dzissa",
        user_firstname: "Thomas",
        pseudo: "Thomas"
    },
    {
        id: 40,
        created_at: "2025-05-31 13:25:13.676898+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "It has increased my level , I can now understand courses very well before the exam",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "It is very helpful and easy ",
        user_name: "KALAMBANI ",
        user_firstname: "Possisso ",
        pseudo: "God'sway"
    },
    {
        id: 35,
        created_at: "2025-05-30 21:47:55.02805+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "It's helped me a lot in my journey, through essay topics and other things.And my way to socialize with others is also to be mentioned",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English Only",
        suggestions: "No suggestion ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Very amazing ",
        user_name: "Kolan",
        user_firstname: "Jeremy",
        pseudo: "Kolan"
    },
    {
        id: 55,
        created_at: "2025-06-04 20:24:56.875426+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "E-learning helped me changed my way to treating exercises and also to improve my intelligence ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "I like more explanation in English ",
        recommendable: "No",
        approve_by_uni: true,
        impressions: "I would like to have in- person sessions to try speaking in front ",
        user_name: "LICTA ",
        user_firstname: "Magnour\u00e9wa",
        pseudo: "Magnour\u00e9wa"
    },
    {
        id: 69,
        created_at: "2025-06-11 06:50:44.453355+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "It helps me not only by improving my marks but also it makes easier to express myself  ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Awesome",
        language_to_speak: "English & French",
        suggestions: "No suggestions ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "The cr\u00e9ation of this website was a really success to me for the first semester till now I really appreciate this initiative by which I personally Excel . Thanks you ",
        user_name: "SALAOU",
        user_firstname: "Hamidath ",
        pseudo: "SALAOU "
    },
    {
        id: 103,
        created_at: "2025-10-17 14:21:44.422118+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "E-learning made my learning so easier, for it provides me with some course explanations and details on one hand and its amazing section of previous exam papers and their corrections on the other hand.",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English Only",
        suggestions: "If novels, plays, short stories, anthologies affiliated with our courses' study can be put on E-learning website for us to download and print them, that will be highly appreciated.",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "An amazing and didactic website \ud83d\udc4c",
        user_name: "KPASSE ",
        user_firstname: "P. Hyacenthe",
        pseudo: "Hyacenthe"
    },
    {
        id: 42,
        created_at: "2025-05-31 15:14:04.049889+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "Courses have became more easy for me",
        happy_register: false,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "May god bless you",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Good",
        user_name: "PEDJEIDOU ",
        user_firstname: "Delphine ",
        pseudo: "PEDJEIDOU "
    },
    {
        id: 36,
        created_at: "2025-05-31 06:52:01.614758+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "It Help me to understand well the course ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Awesome",
        language_to_speak: "English & French",
        suggestions: "To continue to send questions and their answers on WhatsApp groupe ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "E-learning is a good programm that Help student to achieve their GOALS ",
        user_name: "Maxwell ",
        user_firstname: " ESSE ",
        pseudo: "E-member"
    },
    {
        id: 50,
        created_at: "2025-06-02 19:50:38.162444+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "Cela ma aid\u00e9e \u00e0 d\u00e9velopper mes connaissances \n Cela a chang\u00e9 ma mani\u00e8re d'apprentissage ",
        happy_register: true,
        increase_price: false,
        get_more_advantages: false,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Awesome",
        language_to_speak: "English & French",
        suggestions: "Aucune suggestions ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Une tr\u00e8s bonne initiative ",
        user_name: "Kamna",
        user_firstname: "Don'wassou",
        pseudo: "KAMNA Don'wassou "
    },
    {
        id: 53,
        created_at: "2025-06-03 18:27:26.754276+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "La compr\u00e9hension des cours ",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "Aucune suggestion ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Avec e-learning la compr\u00e9hension des cours devient plus facile ",
        user_name: "AGUIM ",
        user_firstname: "Jonas ",
        pseudo: "Jonas "
    },
    {
        id: 73,
        created_at: "2025-06-13 15:02:16.691623+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "It helps me to have a critical mind and to develop my skills ",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: false,
        teach_well: "Good",
        language_to_speak: "English Only",
        suggestions: "No suggestion",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "I would like to get more things there",
        user_name: "Natel ",
        user_firstname: "Lardja ",
        pseudo: "Natel"
    },
    {
        id: 60,
        created_at: "2025-06-06 20:11:06.567052+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "J'arrive \u00e0 mieux comprendre les cours ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "C'est un bon club ",
        user_name: "GNAZOU ",
        user_firstname: "Sylvie ",
        pseudo: "GNAZOU "
    },
    {
        id: 59,
        created_at: "2025-06-06 15:41:33.253997+00",
        Informed_via: "Friends",
        e_importance: false,
        e_help_description: "J'ai bien valid\u00e9 ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Awesome",
        language_to_speak: "English Only",
        suggestions: "La s\u00e9ance d'oral doit se faire chaque samedi ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "\u00c7a aide les \u00e9tudiants de d\u00e9partement ",
        user_name: "KAGA ",
        user_firstname: "Gloria Dibahome ",
        pseudo: "KAGA gloria "
    },
    {
        id: 65,
        created_at: "2025-06-10 07:01:21.22383+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "It Helps me understand more my courses at university ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "All is good",
        user_name: "Piyabalo",
        user_firstname: "Essognina",
        pseudo: "E-member"
    },
     {
        id: 71,
        created_at: "2025-06-12 07:11:27.557407+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "It has helped me to pass easy my courses",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Overall E-learning is a shortcuts Way for students to pass on the courses in three years ",
        user_name: "HEYOU ",
        user_firstname: "Justin ",
        pseudo: "HEYOU "
    },
     {
        id: 80,
        created_at: "2025-06-20 21:58:44.338628+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "It helps me to read my cours",
        happy_register: false,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "It\u2019s very good for students to learn because it\u2019s not everyone who has the chance to follow the entire course",
        user_name: "Marina",
        user_firstname: "Douti",
        pseudo: "E-member"
    },
    {
        id: 82,
        created_at: "2025-06-24 04:59:59.086412+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "D\u00e9veloppement de sagesse",
        happy_register: true,
        increase_price: false,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Awesome",
        language_to_speak: "English & French",
        suggestions: "Aucune suggestion",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Il est super bon",
        user_name: "Tayate",
        user_firstname: "Akosse",
        pseudo: "E-member"
    },
    {
        id: 96,
        created_at: "2025-07-07 20:00:04.74948+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "It has opened my mind so that I can have a good understanding of any new topic now ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "Wonderful ",
        user_name: " BETIYA ",
        user_firstname: "Sapakabia ",
        pseudo: "BETIYA sapakabia"
    },
    {
        id: 85,
        created_at: "2025-06-25 21:58:18.167136+00",
        Informed_via: "Friends",
        e_importance: true,
        e_help_description: "It helps me a lot by handling papers and deals with courses.I remake that things are vert easy for me through E-learning.",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion",
        recommendable: "Sure",
        approve_by_uni: false,
        impressions: "It very  fantastique and i'm proud of it",
        user_name: "DJAGRI",
        user_firstname: "N'grouba",
        pseudo: "Ngrouba"
    },
     {
        id: 94,
        created_at: "2025-06-29 12:36:48.854962+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "I've more, grown and improved",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "I really appreciate the job don\u00e9 here.",
        user_name: "HASSIKPEZI",
        user_firstname: "Josmaine",
        pseudo: "Josmaine "
    },
    {
        id: 104,
        created_at: "2025-10-31 11:01:42.372257+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "It's been helping me through my exams and even more thanks to collected books ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Complicated",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English Only",
        suggestions: "Just more commitment ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "I'm grateful ",
        user_name: "BONI ",
        user_firstname: "N'Poh",
        pseudo: "BONI"
    },
    {
        id: 95,
        created_at: "2025-06-29 14:53:27.031898+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "Mon niveau de compr\u00e9hension ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Easy",
        like_physical_sessions: true,
        teach_well: "Awesome",
        language_to_speak: "English & French",
        suggestions: "Explication des romans en fran\u00e7ais ",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "\u00c7a aide beaucoup ",
        user_name: "Adjikamba ",
        user_firstname: "AKORIGNE ",
        pseudo: "Adjikamba"
    },
    {
        id: 105,
        created_at: "2025-11-25 09:47:23.622291+00",
        Informed_via: "WhatsApp",
        e_importance: true,
        e_help_description: "Increase My skills ",
        happy_register: true,
        increase_price: true,
        get_more_advantages: true,
        e_interaction: "Complicated",
        like_physical_sessions: true,
        teach_well: "Good",
        language_to_speak: "English & French",
        suggestions: "No suggestion",
        recommendable: "Sure",
        approve_by_uni: true,
        impressions: "E-learning the best for students ",
        user_name: "Kansouguiba ",
        user_firstname: "Kansouguiba ",
        pseudo: "Kevin"
    },
]